---

- name: Provision Droplet
  hosts: localhost
  any_errors_fatal: True
  roles:
    - do_droplet

- name: Post-Provisioning Steps (Package Installation/Updates)
  hosts: droplets
  gather_facts: no
  become: true
  any_errors_fatal: True
  pre_tasks:
    - name: Wait for DigitalOcean Post-Boot Config to Complete
      wait_for_connection:
        delay: 60
        timeout: 600
  roles:
    - role: post_provision_common

    - role: antigen
      when: install_antigen == 'yes'

    - role: oh_my_vim
      when: install_oh_my_vim == 'yes'

    - role: homebrew_for_linux
      when: install_linuxbrew == 'yes'

    - role: cli_tools_ng
      when: install_cli_ng_tools == 'yes'

- name: Set up DNS Records
  hosts: droplets
  roles:
    - role: do_domain
      when: create_dns_records == 'yes'
