---

- name: Gather facts
  hosts: all
  any_errors_fatal: True
  tasks:
    - name: Gather facts for ansible_env
      setup:
        fact_path: ansible_env

- name: Provision Droplet
  hosts: localhost
  any_errors_fatal: True
  roles:
    - do_droplet

- name: Post-Provisioning Steps
  hosts: droplets
  gather_facts: no
  become: true
  any_errors_fatal: True
  pre_tasks:
    - name: wait_for_connection
      wait_for_connection:
        delay: 10
        timeout: 600
  roles:
    - post_provision_common