- name: Provision Droplet
  community.digitalocean.digital_ocean_droplet:
    state: present
    name: "{{ do_droplet_name }}"
    oauth_token: "{{ do_api_key }}"
    size: "{{ do_droplet_size }}"
    region: "{{ do_region }}"
    image: "{{ do_image_name }}"
    monitoring: yes
    backups: yes
    wait_timeout: 500
    ssh_keys: "{{ do_ssh_key_fingerprints }}"
  register: my_droplet

- debug:
    msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"

# - name: Ensure a droplet called {{ do_droplet_name }} is present
#   community.digitalocean.digital_ocean_droplet:
#     state: present
#     id: 123
#     name: {{ droplet_name }}
#     oauth_token: {{ do_api_key }}
#     size: 2gb
#     region: {{ do_region }}
#     image: ubuntu-16-04-x64
#     wait_timeout: 500

# - name: Ensure a droplet is present with SSH keys installed
#   community.digitalocean.digital_ocean_droplet:
#     state: present
#     id: 123
#     name: mydroplet
#     oauth_token: XXX
#     size: 2gb
#     region: sfo1
#     ssh_keys: ['1534404', '1784768']
#     image: ubuntu-16-04-x64
#     wait_timeout: 500
