---

- name: Download Oh My Vim! Installer Script
  get_url:
    url: "https://raw.github.com/liangxianzhe/oh-my-vim/master/tools/install.sh"
    dest: "{{ oh_my_vim_installer_tmp }}"
    mode: '0777'

- name: Install Oh My Vim (root)
  command: "/bin/bash -c {{ oh_my_vim_installer_tmp }}"

- name: Install Oh My Vim (Non-Root)
  become: yes
  become_user: "{{ username }}"
  command: "/bin/bash -c {{ oh_my_vim_installer_tmp }}"