---

- name: Create a corresponding subdomain
  community.digitalocean.digital_ocean_domain:
    state: present
    name: "{{ my_droplet.data.name }}.{{ do_domain }}"
    ip: "{{ my_droplet.data.ip_address }}"