---

- name: Update APT package cache
  apt:
    update_cache: yes

- name: Wait Before Continuing to Allow APT to finish
  wait_for:
    timeout: 60

- name: Install Latest Updates from APT
  apt:
    upgrade: dist

- name: Install Some Useful Baseline Packages
  apt:
    pkg: "{{ standard_packages }}"

- name: Create Group For Non-Root User
  group:
    name: "{{ username }}"

- name: Create Non-Root User
  user:
    name: "{{ username }}"
    uid: 1001
    shell: /bin/zsh
    groups: "{{ username }},admin"
    create_home: True
    home: "/home/{{ username }}"