---

antigen_username: "{{ username }}"
antigen_theme: "{{ antigen_theme }}"
antigen_bundles:
  - git
  - command-not-found
  - zsh-navigation-tools
  - ufw
  - zsh_reload
  - zsh-users/zsh-syntax-highlighting
